mobilenet_v3_large with Relu, Adam

In [2]:
import torch
import torchvision
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import torch.nn as nn
import matplotlib.pyplot as plt
from torchinfo import summary
import os
from sklearn.model_selection import train_test_split
from PIL import Image
import torch.optim as optim
from torchvision.models import swin_s
from torchvision.models import mobilenet_v3_large
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from collections import OrderedDict
from tqdm import tqdm

In [12]:
from elpv_reader import load_dataset
images, proba, types = load_dataset()

In [15]:
# check version number
import imblearn
from imblearn.over_sampling import SMOTE

train_set, test_set, train_lables, test_lables = \
train_test_split(images, proba, test_size=0.25,random_state=42)

my_mapping = {0.0:0, 0.3333333333333333:1, 0.6666666666666666:2, 1.0:3}

for i in range(len(train_set)):
    train_lables[i] = my_mapping[train_lables[i]]

for i in range(len(test_set)):
    test_lables[i] = my_mapping[test_lables[i]]

In [16]:
count_list = [0,0,0,0]
for i in range(len(train_set)):
    if train_lables[i] == 0:
        count_list[0] += 1
    if train_lables[i] == 1:
        count_list[1] += 1
    if train_lables[i] == 2:
        count_list[2] += 1
    if train_lables[i] == 3:
        count_list[3] += 1 
for i, j in zip(['The 0.0 has:', 'The 0.33 has:', 'The 0.66 has:', 'The 1.0 has:'], count_list):
    print(i, j)

The 0.0 has: 1136
The 0.33 has: 222
The 0.66 has: 75
The 1.0 has: 535


In [17]:
class CustomDataset(Dataset):
    def __init__(self, images, labels, transform=False):
        self.images = images
        self.label_mapping = {0: np.eye(4)[0], 1: np.eye(4)[1],\
                              2: np.eye(4)[2], 3: np.eye(4)[3]}
        self.labels = [self.label_mapping[label] for label in labels]
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        label = self.labels[idx]
        image = Image.fromarray(image)

        # 如果图像为灰度图像，将其复制到三个通道，转换为 RGB 图像
        if image.mode == 'L':
            image = image.convert('RGB')

        if self.transform:
            image = self.transform(image)
        return image, label


transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
    ])


custom_train_dataset = CustomDataset(train_set, train_lables, transform)
custom_test_dataset = CustomDataset(test_set, test_lables, transform)


batch_size = 32
train_loader = DataLoader(custom_train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(custom_test_dataset, batch_size=batch_size, shuffle=False)

In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")  
else:
    device = torch.device("cpu")  

model = mobilenet_v3_large(weights=True)

classifier1 = nn.Sequential(OrderedDict([('fc1', nn.Linear(960, 4)),
                           ('output', nn.ReLU())
                          ]))
    
model.classifier = classifier1

model.to(device)
print()

d:\anaconda\envs\torchtest\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V3_Large_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V3_Large_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [19]:

lossfunc = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-5)

save_path = '.\model.pth'
best_accuracy = 79
num_epochs = 20
for epoch in range(num_epochs):
    model.train()
    train_loss = 0
    for inputs, labels in tqdm(train_loader):
        inputs, labels = inputs.to(device), labels.to(device)  # 移动数据到 CUDA
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = lossfunc(outputs, labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    train_loss = train_loss / len(train_loader)
    print(f'Epoch {epoch + 1}/{num_epochs} - Training Loss: {train_loss:.4f}')


    model.eval()
    all_predictions = []
    all_labels = []
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)  
            outputs = model(inputs)
            _, predictions = torch.max(outputs, 1)
            _, real_labels = torch.max(labels, 1)
            all_predictions.extend(predictions.cpu().numpy())
            all_labels.extend(real_labels.cpu().numpy())

    
    accuracy = accuracy_score(all_labels, all_predictions)
    conf_matrix = confusion_matrix(all_labels, all_predictions)

    if best_accuracy < accuracy:
        best_accuracy = accuracy
        torch.save(model.state_dict(), save_path)
        print(f'Epoch [{epoch + 1}/{num_epochs}] - Saved Best Model (Best Accuracy: {best_accuracy:.4f})')

    print(f'Accuracy: {accuracy:.4f}')
    print('Confusion Matrix:')
    print(conf_matrix)

100%|██████████| 62/62 [00:09<00:00,  6.79it/s]


Epoch 1/20 - Training Loss: 1.3146
Accuracy: 0.3552
Confusion Matrix:
[[134 198   2  38]
 [ 21  38   2  12]
 [ 17  10   1   3]
 [ 52  68   0  60]]


100%|██████████| 62/62 [00:06<00:00, 10.29it/s]


Epoch 2/20 - Training Loss: 1.1848
Accuracy: 0.2576
Confusion Matrix:
[[ 47  89   1 235]
 [  4  22   0  47]
 [  1   9   0  21]
 [ 16  64   0 100]]


100%|██████████| 62/62 [00:05<00:00, 10.39it/s]


Epoch 3/20 - Training Loss: 1.0680
Accuracy: 0.2698
Confusion Matrix:
[[ 62 103   2 205]
 [  7  21   0  45]
 [  1  13   0  17]
 [ 34  52   0  94]]


100%|██████████| 62/62 [00:05<00:00, 10.42it/s]


Epoch 4/20 - Training Loss: 0.9788
Accuracy: 0.3293
Confusion Matrix:
[[ 94  62   0 216]
 [ 18  12   0  43]
 [  3   5   0  23]
 [ 46  23   1 110]]


100%|██████████| 62/62 [00:06<00:00,  9.91it/s]


Epoch 5/20 - Training Loss: 0.9175
Accuracy: 0.4497
Confusion Matrix:
[[151  10   1 210]
 [ 25   1   0  47]
 [  4   2   0  25]
 [ 20  17   0 143]]


100%|██████████| 62/62 [00:06<00:00,  9.46it/s]


Epoch 6/20 - Training Loss: 0.8825
Accuracy: 0.5777
Confusion Matrix:
[[222   3   1 146]
 [ 36   0   0  37]
 [ 11   1   0  19]
 [ 19   3   1 157]]


100%|██████████| 62/62 [00:06<00:00,  9.21it/s]


Epoch 7/20 - Training Loss: 0.8490
Accuracy: 0.6494
Confusion Matrix:
[[269   0   0 103]
 [ 48   0   0  25]
 [ 12   0   0  19]
 [ 23   0   0 157]]


100%|██████████| 62/62 [00:06<00:00,  9.10it/s]


Epoch 8/20 - Training Loss: 0.8233
Accuracy: 0.6845
Confusion Matrix:
[[297   1   0  74]
 [ 49   0   0  24]
 [ 16   0   0  15]
 [ 28   0   0 152]]


100%|██████████| 62/62 [00:06<00:00,  9.30it/s]


Epoch 9/20 - Training Loss: 0.7938
Accuracy: 0.6799
Confusion Matrix:
[[300   1   0  71]
 [ 54   0   0  19]
 [ 18   0   0  13]
 [ 34   0   0 146]]


100%|██████████| 62/62 [00:06<00:00,  9.04it/s]


Epoch 10/20 - Training Loss: 0.7768
Accuracy: 0.6860
Confusion Matrix:
[[307   1   0  64]
 [ 58   0   0  15]
 [ 20   0   0  11]
 [ 37   0   0 143]]


100%|██████████| 62/62 [00:06<00:00,  9.05it/s]


Epoch 11/20 - Training Loss: 0.7486
Accuracy: 0.6966
Confusion Matrix:
[[317   1   0  54]
 [ 59   0   0  14]
 [ 23   1   0   7]
 [ 40   0   0 140]]


100%|██████████| 62/62 [00:06<00:00,  9.17it/s]


Epoch 12/20 - Training Loss: 0.7430
Accuracy: 0.7134
Confusion Matrix:
[[334   1   0  37]
 [ 67   0   0   6]
 [ 25   1   0   5]
 [ 46   0   0 134]]


100%|██████████| 62/62 [00:06<00:00,  9.11it/s]


Epoch 13/20 - Training Loss: 0.7143
Accuracy: 0.7119
Confusion Matrix:
[[336   1   0  35]
 [ 67   1   0   5]
 [ 25   1   0   5]
 [ 50   0   0 130]]


100%|██████████| 62/62 [00:06<00:00,  9.32it/s]


Epoch 14/20 - Training Loss: 0.6909
Accuracy: 0.7119
Confusion Matrix:
[[337   1   0  34]
 [ 65   2   0   6]
 [ 26   0   0   5]
 [ 51   1   0 128]]


100%|██████████| 62/62 [00:06<00:00,  9.04it/s]


Epoch 15/20 - Training Loss: 0.6645
Accuracy: 0.7210
Confusion Matrix:
[[341   3   0  28]
 [ 67   3   0   3]
 [ 27   1   0   3]
 [ 50   1   0 129]]


100%|██████████| 62/62 [00:06<00:00,  9.03it/s]


Epoch 16/20 - Training Loss: 0.6550
Accuracy: 0.7226
Confusion Matrix:
[[343   3   0  26]
 [ 64   4   0   5]
 [ 27   1   0   3]
 [ 51   2   0 127]]


100%|██████████| 62/62 [00:07<00:00,  8.85it/s]


Epoch 17/20 - Training Loss: 0.6247
Accuracy: 0.7271
Confusion Matrix:
[[344   4   0  24]
 [ 63   5   0   5]
 [ 26   0   0   5]
 [ 49   3   0 128]]


100%|██████████| 62/62 [00:06<00:00,  9.19it/s]


Epoch 18/20 - Training Loss: 0.6041
Accuracy: 0.7317
Confusion Matrix:
[[346   4   0  22]
 [ 62   6   0   5]
 [ 26   0   0   5]
 [ 49   3   0 128]]


100%|██████████| 62/62 [00:07<00:00,  8.71it/s]


Epoch 19/20 - Training Loss: 0.5760
Accuracy: 0.7348
Confusion Matrix:
[[348   4   0  20]
 [ 57   9   1   6]
 [ 25   0   0   6]
 [ 51   4   0 125]]


100%|██████████| 62/62 [00:06<00:00,  9.83it/s]


Epoch 20/20 - Training Loss: 0.5657
Accuracy: 0.7378
Confusion Matrix:
[[348   4   0  20]
 [ 56   9   1   7]
 [ 26   0   0   5]
 [ 49   4   0 127]]


In [20]:
# 创建两个子集，分别存储mono和poly的标签和预测
mono_subset_labels = [label for label, img_type in zip(all_labels, types) if img_type == "mono"]
mono_subset_predictions = [pred for pred, img_type in zip(all_predictions, types) if img_type == "mono"]
poly_subset_labels = [label for label, img_type in zip(all_labels, types) if img_type == "poly"]
poly_subset_predictions = [pred for pred, img_type in zip(all_predictions, types) if img_type == "poly"]

# 计算不同类型的准确率和混淆矩阵
accuracy = accuracy_score(all_labels, all_predictions)
accuracy_mono = accuracy_score(mono_subset_labels, mono_subset_predictions)
accuracy_poly = accuracy_score(poly_subset_labels, poly_subset_predictions)
conf_matrix = confusion_matrix(all_labels, all_predictions)
conf_matrix_mono = confusion_matrix(mono_subset_labels, mono_subset_predictions)
conf_matrix_poly = confusion_matrix(poly_subset_labels, poly_subset_predictions)
f1_total = f1_score(all_labels, all_predictions, average='macro')
f1_mono = f1_score(mono_subset_labels, mono_subset_predictions, average='macro')
f1_poly = f1_score(poly_subset_labels, poly_subset_predictions, average='macro')

print('The total accuracy is:', accuracy)
print()
print('The accuracy of mono type is:', accuracy_mono)
print()
print('The accuracy of poly type is:', accuracy_poly)
print()
print('The total confusion matrix is:\n', conf_matrix)
print()
print('The confusion matrix of mono type is:\n', conf_matrix_mono)
print()
print('The confusion matrix of poly type is:\n', conf_matrix_poly)
print()
print('The total F1 Score is:', f1_total)
print()
print('The F1 Score of mono type is:', f1_mono)
print()
print('The F1 Score of poly type is:', f1_poly)


The total accuracy is: 0.7378048780487805

The accuracy of mono type is: 0.7083333333333334

The accuracy of poly type is: 0.7548076923076923

The total confusion matrix is:
 [[348   4   0  20]
 [ 56   9   1   7]
 [ 26   0   0   5]
 [ 49   4   0 127]]

The confusion matrix of mono type is:
 [[125   1   0   8]
 [ 23   1   1   4]
 [ 10   0   0   2]
 [ 19   2   0  44]]

The confusion matrix of poly type is:
 [[223   3   0  12]
 [ 33   8   0   3]
 [ 16   0   0   3]
 [ 30   2   0  83]]

The total F1 Score is: 0.4417809691184066

The F1 Score of mono type is: 0.39497793399448167

The F1 Score of poly type is: 0.46878654970760236
