mobilenet_v3_large with softmax, Adam

In [1]:
import torch
import torchvision
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import torch.nn as nn
import matplotlib.pyplot as plt
from torchinfo import summary
import os
from sklearn.model_selection import train_test_split
from PIL import Image
import torch.optim as optim
from torchvision.models import swin_s
from torchvision.models import mobilenet_v3_large
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from collections import OrderedDict
from tqdm import tqdm

In [2]:
from elpv_reader import load_dataset
images, proba, types = load_dataset()

In [3]:
# check version number
import imblearn
from imblearn.over_sampling import SMOTE

train_set, test_set, train_lables, test_lables = \
train_test_split(images, proba, test_size=0.25,random_state=42)

my_mapping = {0.0:0, 0.3333333333333333:1, 0.6666666666666666:2, 1.0:3}

for i in range(len(train_set)):
    train_lables[i] = my_mapping[train_lables[i]]

for i in range(len(test_set)):
    test_lables[i] = my_mapping[test_lables[i]]

In [4]:
count_list = [0,0,0,0]
for i in range(len(train_set)):
    if train_lables[i] == 0:
        count_list[0] += 1
    if train_lables[i] == 1:
        count_list[1] += 1
    if train_lables[i] == 2:
        count_list[2] += 1
    if train_lables[i] == 3:
        count_list[3] += 1 
for i, j in zip(['The 0.0 has:', 'The 0.33 has:', 'The 0.66 has:', 'The 1.0 has:'], count_list):
    print(i, j)

The 0.0 has: 1136
The 0.33 has: 222
The 0.66 has: 75
The 1.0 has: 535


In [5]:
class CustomDataset(Dataset):
    def __init__(self, images, labels, transform=False):
        self.images = images
        self.label_mapping = {0: np.eye(4)[0], 1: np.eye(4)[1],\
                              2: np.eye(4)[2], 3: np.eye(4)[3]}
        self.labels = [self.label_mapping[label] for label in labels]
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        label = self.labels[idx]
        image = Image.fromarray(image)

        # 如果图像为灰度图像，将其复制到三个通道，转换为 RGB 图像
        if image.mode == 'L':
            image = image.convert('RGB')

        if self.transform:
            image = self.transform(image)
        return image, label


transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
    ])


custom_train_dataset = CustomDataset(train_set, train_lables, transform)
custom_test_dataset = CustomDataset(test_set, test_lables, transform)


batch_size = 32
train_loader = DataLoader(custom_train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(custom_test_dataset, batch_size=batch_size, shuffle=False)

In [6]:
if torch.cuda.is_available():
    device = torch.device("cuda")  
else:
    device = torch.device("cpu")  

model = mobilenet_v3_large(weights=True)

classifier1 = nn.Sequential(OrderedDict([('fc1', nn.Linear(960, 4)),
                           ('output', nn.Softmax())
                          ]))
    
model.classifier = classifier1

model.to(device)
print()

d:\anaconda\envs\torchtest\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V3_Large_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V3_Large_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [7]:

lossfunc = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

save_path = '.\model.pth'
best_accuracy = 79
num_epochs = 20
for epoch in range(num_epochs):
    model.train()
    train_loss = 0
    for inputs, labels in tqdm(train_loader):
        inputs, labels = inputs.to(device), labels.to(device)  # 移动数据到 CUDA
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = lossfunc(outputs, labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    train_loss = train_loss / len(train_loader)
    print(f'Epoch {epoch + 1}/{num_epochs} - Training Loss: {train_loss:.4f}')


    model.eval()
    all_predictions = []
    all_labels = []
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)  
            outputs = model(inputs)
            _, predictions = torch.max(outputs, 1)
            _, real_labels = torch.max(labels, 1)
            all_predictions.extend(predictions.cpu().numpy())
            all_labels.extend(real_labels.cpu().numpy())

    
    accuracy = accuracy_score(all_labels, all_predictions)
    conf_matrix = confusion_matrix(all_labels, all_predictions)

    if best_accuracy < accuracy:
        best_accuracy = accuracy
        torch.save(model.state_dict(), save_path)
        print(f'Epoch [{epoch + 1}/{num_epochs}] - Saved Best Model (Best Accuracy: {best_accuracy:.4f})')

    print(f'Accuracy: {accuracy:.4f}')
    print('Confusion Matrix:')
    print(conf_matrix)

  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:08<00:00,  6.89it/s]


Epoch 1/20 - Training Loss: 1.4357
Accuracy: 0.2180
Confusion Matrix:
[[ 95   0 276   1]
 [ 17   0  56   0]
 [  9   0  22   0]
 [ 72   0  82  26]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00, 10.26it/s]


Epoch 2/20 - Training Loss: 1.3652
Accuracy: 0.2912
Confusion Matrix:
[[138   0 114 120]
 [ 23   0  29  21]
 [ 16   0   2  13]
 [ 93   5  31  51]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.87it/s]


Epoch 3/20 - Training Loss: 1.2830
Accuracy: 0.3308
Confusion Matrix:
[[122  10  78 162]
 [ 18   1  17  37]
 [  9   3   8  11]
 [ 65   5  24  86]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.60it/s]


Epoch 4/20 - Training Loss: 1.2086
Accuracy: 0.4146
Confusion Matrix:
[[150   1  16 205]
 [ 23   1   7  42]
 [ 14   1   2  14]
 [ 54   3   4 119]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.22it/s]


Epoch 5/20 - Training Loss: 1.1568
Accuracy: 0.4436
Confusion Matrix:
[[160   0   3 209]
 [ 27   0   0  46]
 [  6   0   0  25]
 [ 47   0   2 131]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.19it/s]


Epoch 6/20 - Training Loss: 1.1184
Accuracy: 0.6082
Confusion Matrix:
[[244   0   1 127]
 [ 37   1   0  35]
 [ 10   0   1  20]
 [ 27   0   0 153]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.17it/s]


Epoch 7/20 - Training Loss: 1.0964
Accuracy: 0.6585
Confusion Matrix:
[[297   4   0  71]
 [ 51   2   0  20]
 [ 16   0   0  15]
 [ 47   0   0 133]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  8.90it/s]


Epoch 8/20 - Training Loss: 1.0829
Accuracy: 0.6753
Confusion Matrix:
[[318   1   0  53]
 [ 56   1   0  16]
 [ 19   0   0  12]
 [ 56   0   0 124]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.50it/s]


Epoch 9/20 - Training Loss: 1.0682
Accuracy: 0.6799
Confusion Matrix:
[[327   1   0  44]
 [ 63   1   0   9]
 [ 22   0   0   9]
 [ 62   0   0 118]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.78it/s]


Epoch 10/20 - Training Loss: 1.0570
Accuracy: 0.6845
Confusion Matrix:
[[332   1   0  39]
 [ 63   1   0   9]
 [ 24   0   0   7]
 [ 64   0   0 116]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.81it/s]


Epoch 11/20 - Training Loss: 1.0470
Accuracy: 0.6890
Confusion Matrix:
[[332   2   0  38]
 [ 62   2   0   9]
 [ 24   0   0   7]
 [ 62   0   0 118]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.72it/s]


Epoch 12/20 - Training Loss: 1.0372
Accuracy: 0.6921
Confusion Matrix:
[[333   2   0  37]
 [ 63   2   0   8]
 [ 25   0   0   6]
 [ 61   0   0 119]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.72it/s]


Epoch 13/20 - Training Loss: 1.0265
Accuracy: 0.6982
Confusion Matrix:
[[337   4   0  31]
 [ 62   2   0   9]
 [ 26   0   0   5]
 [ 61   0   0 119]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.72it/s]


Epoch 14/20 - Training Loss: 1.0151
Accuracy: 0.6997
Confusion Matrix:
[[337   6   0  29]
 [ 63   3   0   7]
 [ 26   0   0   5]
 [ 61   0   0 119]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.76it/s]


Epoch 15/20 - Training Loss: 1.0078
Accuracy: 0.7088
Confusion Matrix:
[[340   3   0  29]
 [ 65   4   0   4]
 [ 26   0   0   5]
 [ 59   0   0 121]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.61it/s]


Epoch 16/20 - Training Loss: 0.9992
Accuracy: 0.7210
Confusion Matrix:
[[343   3   0  26]
 [ 61   6   0   6]
 [ 26   0   0   5]
 [ 56   0   0 124]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.82it/s]


Epoch 17/20 - Training Loss: 0.9927
Accuracy: 0.7226
Confusion Matrix:
[[346   3   0  23]
 [ 61   6   0   6]
 [ 27   0   0   4]
 [ 58   0   0 122]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.87it/s]


Epoch 18/20 - Training Loss: 0.9721
Accuracy: 0.7363
Confusion Matrix:
[[346   4   0  22]
 [ 59   8   0   6]
 [ 25   0   0   6]
 [ 51   0   0 129]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.75it/s]


Epoch 19/20 - Training Loss: 0.9672
Accuracy: 0.7363
Confusion Matrix:
[[349   3   0  20]
 [ 59   8   0   6]
 [ 25   0   0   6]
 [ 54   0   0 126]]


  0%|          | 0/62 [00:00<?, ?it/s]d:\anaconda\envs\torchtest\lib\site-packages\torch\nn\modules\container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
100%|██████████| 62/62 [00:06<00:00,  9.81it/s]


Epoch 20/20 - Training Loss: 0.9615
Accuracy: 0.7409
Confusion Matrix:
[[351   1   0  20]
 [ 58   8   0   7]
 [ 23   0   0   8]
 [ 53   0   0 127]]


In [8]:
# 创建两个子集，分别存储mono和poly的标签和预测
mono_subset_labels = [label for label, img_type in zip(all_labels, types) if img_type == "mono"]
mono_subset_predictions = [pred for pred, img_type in zip(all_predictions, types) if img_type == "mono"]
poly_subset_labels = [label for label, img_type in zip(all_labels, types) if img_type == "poly"]
poly_subset_predictions = [pred for pred, img_type in zip(all_predictions, types) if img_type == "poly"]

# 计算不同类型的准确率和混淆矩阵
accuracy = accuracy_score(all_labels, all_predictions)
accuracy_mono = accuracy_score(mono_subset_labels, mono_subset_predictions)
accuracy_poly = accuracy_score(poly_subset_labels, poly_subset_predictions)
conf_matrix = confusion_matrix(all_labels, all_predictions)
conf_matrix_mono = confusion_matrix(mono_subset_labels, mono_subset_predictions)
conf_matrix_poly = confusion_matrix(poly_subset_labels, poly_subset_predictions)
f1_total = f1_score(all_labels, all_predictions, average='macro')
f1_mono = f1_score(mono_subset_labels, mono_subset_predictions, average='macro')
f1_poly = f1_score(poly_subset_labels, poly_subset_predictions, average='macro')

print('The total accuracy is:', accuracy)
print()
print('The accuracy of mono type is:', accuracy_mono)
print()
print('The accuracy of poly type is:', accuracy_poly)
print()
print('The total confusion matrix is:\n', conf_matrix)
print()
print('The confusion matrix of mono type is:\n', conf_matrix_mono)
print()
print('The confusion matrix of poly type is:\n', conf_matrix_poly)
print()
print('The total F1 Score is:', f1_total)
print()
print('The F1 Score of mono type is:', f1_mono)
print()
print('The F1 Score of poly type is:', f1_poly)


The total accuracy is: 0.7408536585365854

The accuracy of mono type is: 0.7

The accuracy of poly type is: 0.7644230769230769

The total confusion matrix is:
 [[351   1   0  20]
 [ 58   8   0   7]
 [ 23   0   0   8]
 [ 53   0   0 127]]

The confusion matrix of mono type is:
 [[125   0   0   9]
 [ 25   2   0   2]
 [  9   0   0   3]
 [ 24   0   0  41]]

The confusion matrix of poly type is:
 [[226   1   0  11]
 [ 33   6   0   5]
 [ 14   0   0   5]
 [ 29   0   0  86]]

The total F1 Score is: 0.4392371331132092

The F1 Score of mono type is: 0.40025228113021943

The F1 Score of poly type is: 0.4617764823647177
